// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: coordinator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoordinatorUpsertItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorUpsertItem) Reset() {
	*x = CoordinatorUpsertItem{}
	mi := &file_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorUpsertItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorUpsertItem) ProtoMessage() {}

func (x *CoordinatorUpsertItem) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorUpsertItem.ProtoReflect.Descriptor instead.
func (*CoordinatorUpsertItem) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinatorUpsertItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CoordinatorUpsertItem) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *CoordinatorUpsertItem) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type CoordinatorSearchResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RawText         string                 `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CoordinatorSearchResult) Reset() {
	*x = CoordinatorSearchResult{}
	mi := &file_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorSearchResult) ProtoMessage() {}

func (x *CoordinatorSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorSearchResult.ProtoReflect.Descriptor instead.
func (*CoordinatorSearchResult) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *CoordinatorSearchResult) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *CoordinatorSearchResult) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

type CoordinatorUpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CoordinatorUpsertItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorUpsertRequest) Reset() {
	*x = CoordinatorUpsertRequest{}
	mi := &file_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorUpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorUpsertRequest) ProtoMessage() {}

func (x *CoordinatorUpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorUpsertRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorUpsertRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinatorUpsertRequest) GetItem() *CoordinatorUpsertItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type CoordinatorUpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorUpsertResponse) Reset() {
	*x = CoordinatorUpsertResponse{}
	mi := &file_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorUpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorUpsertResponse) ProtoMessage() {}

func (x *CoordinatorUpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorUpsertResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorUpsertResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{3}
}

type CoordinatorUpsertBatchRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*CoordinatorUpsertItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorUpsertBatchRequest) Reset() {
	*x = CoordinatorUpsertBatchRequest{}
	mi := &file_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorUpsertBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorUpsertBatchRequest) ProtoMessage() {}

func (x *CoordinatorUpsertBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorUpsertBatchRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorUpsertBatchRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CoordinatorUpsertBatchRequest) GetItems() []*CoordinatorUpsertItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CoordinatorUpsertBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorUpsertBatchResponse) Reset() {
	*x = CoordinatorUpsertBatchResponse{}
	mi := &file_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorUpsertBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorUpsertBatchResponse) ProtoMessage() {}

func (x *CoordinatorUpsertBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorUpsertBatchResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorUpsertBatchResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{5}
}

type CoordinatorSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorSearchRequest) Reset() {
	*x = CoordinatorSearchRequest{}
	mi := &file_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorSearchRequest) ProtoMessage() {}

func (x *CoordinatorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorSearchRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorSearchRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *CoordinatorSearchRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *CoordinatorSearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type CoordinatorSearchResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Results       []*CoordinatorSearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorSearchResponse) Reset() {
	*x = CoordinatorSearchResponse{}
	mi := &file_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorSearchResponse) ProtoMessage() {}

func (x *CoordinatorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorSearchResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorSearchResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *CoordinatorSearchResponse) GetResults() []*CoordinatorSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CoordinatorCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorCountRequest) Reset() {
	*x = CoordinatorCountRequest{}
	mi := &file_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorCountRequest) ProtoMessage() {}

func (x *CoordinatorCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorCountRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorCountRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{8}
}

type CoordinatorCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorCountResponse) Reset() {
	*x = CoordinatorCountResponse{}
	mi := &file_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorCountResponse) ProtoMessage() {}

func (x *CoordinatorCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorCountResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorCountResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *CoordinatorCountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CoordinatorHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       string                 `protobuf:"bytes,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorHeartbeatRequest) Reset() {
	*x = CoordinatorHeartbeatRequest{}
	mi := &file_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorHeartbeatRequest) ProtoMessage() {}

func (x *CoordinatorHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*CoordinatorHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *CoordinatorHeartbeatRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type CoordinatorHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordinatorHeartbeatResponse) Reset() {
	*x = CoordinatorHeartbeatResponse{}
	mi := &file_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinatorHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinatorHeartbeatResponse) ProtoMessage() {}

func (x *CoordinatorHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinatorHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*CoordinatorHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_coordinator_proto_rawDescGZIP(), []int{11}
}

var File_coordinator_proto protoreflect.FileDescriptor

const file_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x11coordinator.proto\x12\x05argus\"`\n" +
	"\x15CoordinatorUpsertItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\"_\n" +
	"\x17CoordinatorSearchResult\x12\x19\n" +
	"\braw_text\x18\x01 \x01(\tR\arawText\x12)\n" +
	"\x10similarity_score\x18\x02 \x01(\x01R\x0fsimilarityScore\"L\n" +
	"\x18CoordinatorUpsertRequest\x120\n" +
	"\x04item\x18\x01 \x01(\v2\x1c.argus.CoordinatorUpsertItemR\x04item\"\x1b\n" +
	"\x19CoordinatorUpsertResponse\"S\n" +
	"\x1dCoordinatorUpsertBatchRequest\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.argus.CoordinatorUpsertItemR\x05items\" \n" +
	"\x1eCoordinatorUpsertBatchResponse\"M\n" +
	"\x18CoordinatorSearchRequest\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"U\n" +
	"\x19CoordinatorSearchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.argus.CoordinatorSearchResultR\aresults\"\x19\n" +
	"\x17CoordinatorCountRequest\"0\n" +
	"\x18CoordinatorCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"8\n" +
	"\x1bCoordinatorHeartbeatRequest\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\tR\ashardId\"\x1e\n" +
	"\x1cCoordinatorHeartbeatResponse2\xaa\x03\n" +
	"\x12CoordinatorService\x12K\n" +
	"\x06Upsert\x12\x1f.argus.CoordinatorUpsertRequest\x1a .argus.CoordinatorUpsertResponse\x12Z\n" +
	"\vUpsertBatch\x12$.argus.CoordinatorUpsertBatchRequest\x1a%.argus.CoordinatorUpsertBatchResponse\x12K\n" +
	"\x06Search\x12\x1f.argus.CoordinatorSearchRequest\x1a .argus.CoordinatorSearchResponse\x12H\n" +
	"\x05Count\x12\x1e.argus.CoordinatorCountRequest\x1a\x1f.argus.CoordinatorCountResponse\x12T\n" +
	"\tHeartbeat\x12\".argus.CoordinatorHeartbeatRequest\x1a#.argus.CoordinatorHeartbeatResponseB\x1bZ\x19github.com/aepii/argus/pbb\x06proto3"

var (
	file_coordinator_proto_rawDescOnce sync.Once
	file_coordinator_proto_rawDescData []byte
)

func file_coordinator_proto_rawDescGZIP() []byte {
	file_coordinator_proto_rawDescOnce.Do(func() {
		file_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)))
	})
	return file_coordinator_proto_rawDescData
}

var file_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_coordinator_proto_goTypes = []any{
	(*CoordinatorUpsertItem)(nil),          // 0: argus.CoordinatorUpsertItem
	(*CoordinatorSearchResult)(nil),        // 1: argus.CoordinatorSearchResult
	(*CoordinatorUpsertRequest)(nil),       // 2: argus.CoordinatorUpsertRequest
	(*CoordinatorUpsertResponse)(nil),      // 3: argus.CoordinatorUpsertResponse
	(*CoordinatorUpsertBatchRequest)(nil),  // 4: argus.CoordinatorUpsertBatchRequest
	(*CoordinatorUpsertBatchResponse)(nil), // 5: argus.CoordinatorUpsertBatchResponse
	(*CoordinatorSearchRequest)(nil),       // 6: argus.CoordinatorSearchRequest
	(*CoordinatorSearchResponse)(nil),      // 7: argus.CoordinatorSearchResponse
	(*CoordinatorCountRequest)(nil),        // 8: argus.CoordinatorCountRequest
	(*CoordinatorCountResponse)(nil),       // 9: argus.CoordinatorCountResponse
	(*CoordinatorHeartbeatRequest)(nil),    // 10: argus.CoordinatorHeartbeatRequest
	(*CoordinatorHeartbeatResponse)(nil),   // 11: argus.CoordinatorHeartbeatResponse
}
var file_coordinator_proto_depIdxs = []int32{
	0,  // 0: argus.CoordinatorUpsertRequest.item:type_name -> argus.CoordinatorUpsertItem
	0,  // 1: argus.CoordinatorUpsertBatchRequest.items:type_name -> argus.CoordinatorUpsertItem
	1,  // 2: argus.CoordinatorSearchResponse.results:type_name -> argus.CoordinatorSearchResult
	2,  // 3: argus.CoordinatorService.Upsert:input_type -> argus.CoordinatorUpsertRequest
	4,  // 4: argus.CoordinatorService.UpsertBatch:input_type -> argus.CoordinatorUpsertBatchRequest
	6,  // 5: argus.CoordinatorService.Search:input_type -> argus.CoordinatorSearchRequest
	8,  // 6: argus.CoordinatorService.Count:input_type -> argus.CoordinatorCountRequest
	10, // 7: argus.CoordinatorService.Heartbeat:input_type -> argus.CoordinatorHeartbeatRequest
	3,  // 8: argus.CoordinatorService.Upsert:output_type -> argus.CoordinatorUpsertResponse
	5,  // 9: argus.CoordinatorService.UpsertBatch:output_type -> argus.CoordinatorUpsertBatchResponse
	7,  // 10: argus.CoordinatorService.Search:output_type -> argus.CoordinatorSearchResponse
	9,  // 11: argus.CoordinatorService.Count:output_type -> argus.CoordinatorCountResponse
	11, // 12: argus.CoordinatorService.Heartbeat:output_type -> argus.CoordinatorHeartbeatResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_coordinator_proto_init() }
func file_coordinator_proto_init() {
	if File_coordinator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coordinator_proto_rawDesc), len(file_coordinator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coordinator_proto_goTypes,
		DependencyIndexes: file_coordinator_proto_depIdxs,
		MessageInfos:      file_coordinator_proto_msgTypes,
	}.Build()
	File_coordinator_proto = out.File
	file_coordinator_proto_goTypes = nil
	file_coordinator_proto_depIdxs = nil
}
