// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: coordinator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_Upsert_FullMethodName      = "/argus.CoordinatorService/Upsert"
	CoordinatorService_UpsertBatch_FullMethodName = "/argus.CoordinatorService/UpsertBatch"
	CoordinatorService_Search_FullMethodName      = "/argus.CoordinatorService/Search"
	CoordinatorService_Count_FullMethodName       = "/argus.CoordinatorService/Count"
	CoordinatorService_Heartbeat_FullMethodName   = "/argus.CoordinatorService/Heartbeat"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	Upsert(ctx context.Context, in *CoordinatorUpsertRequest, opts ...grpc.CallOption) (*CoordinatorUpsertResponse, error)
	UpsertBatch(ctx context.Context, in *CoordinatorUpsertBatchRequest, opts ...grpc.CallOption) (*CoordinatorUpsertBatchResponse, error)
	Search(ctx context.Context, in *CoordinatorSearchRequest, opts ...grpc.CallOption) (*CoordinatorSearchResponse, error)
	Count(ctx context.Context, in *CoordinatorCountRequest, opts ...grpc.CallOption) (*CoordinatorCountResponse, error)
	Heartbeat(ctx context.Context, in *CoordinatorHeartbeatRequest, opts ...grpc.CallOption) (*CoordinatorHeartbeatResponse, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) Upsert(ctx context.Context, in *CoordinatorUpsertRequest, opts ...grpc.CallOption) (*CoordinatorUpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorUpsertResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) UpsertBatch(ctx context.Context, in *CoordinatorUpsertBatchRequest, opts ...grpc.CallOption) (*CoordinatorUpsertBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorUpsertBatchResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_UpsertBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Search(ctx context.Context, in *CoordinatorSearchRequest, opts ...grpc.CallOption) (*CoordinatorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorSearchResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Count(ctx context.Context, in *CoordinatorCountRequest, opts ...grpc.CallOption) (*CoordinatorCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorCountResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) Heartbeat(ctx context.Context, in *CoordinatorHeartbeatRequest, opts ...grpc.CallOption) (*CoordinatorHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoordinatorHeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
type CoordinatorServiceServer interface {
	Upsert(context.Context, *CoordinatorUpsertRequest) (*CoordinatorUpsertResponse, error)
	UpsertBatch(context.Context, *CoordinatorUpsertBatchRequest) (*CoordinatorUpsertBatchResponse, error)
	Search(context.Context, *CoordinatorSearchRequest) (*CoordinatorSearchResponse, error)
	Count(context.Context, *CoordinatorCountRequest) (*CoordinatorCountResponse, error)
	Heartbeat(context.Context, *CoordinatorHeartbeatRequest) (*CoordinatorHeartbeatResponse, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) Upsert(context.Context, *CoordinatorUpsertRequest) (*CoordinatorUpsertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedCoordinatorServiceServer) UpsertBatch(context.Context, *CoordinatorUpsertBatchRequest) (*CoordinatorUpsertBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertBatch not implemented")
}
func (UnimplementedCoordinatorServiceServer) Search(context.Context, *CoordinatorSearchRequest) (*CoordinatorSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedCoordinatorServiceServer) Count(context.Context, *CoordinatorCountRequest) (*CoordinatorCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedCoordinatorServiceServer) Heartbeat(context.Context, *CoordinatorHeartbeatRequest) (*CoordinatorHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Upsert(ctx, req.(*CoordinatorUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_UpsertBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorUpsertBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).UpsertBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_UpsertBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).UpsertBatch(ctx, req.(*CoordinatorUpsertBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Search(ctx, req.(*CoordinatorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Count(ctx, req.(*CoordinatorCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoordinatorHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Heartbeat(ctx, req.(*CoordinatorHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "argus.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _CoordinatorService_Upsert_Handler,
		},
		{
			MethodName: "UpsertBatch",
			Handler:    _CoordinatorService_UpsertBatch_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _CoordinatorService_Search_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _CoordinatorService_Count_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinatorService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator.proto",
}
