// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: vector_store.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RawText         string                 `protobuf:"bytes,1,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	SimilarityScore float64                `protobuf:"fixed64,2,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_vector_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResult) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *SearchResult) GetSimilarityScore() float64 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

type UpsertItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RawText       string                 `protobuf:"bytes,2,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,3,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertItem) Reset() {
	*x = UpsertItem{}
	mi := &file_vector_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertItem) ProtoMessage() {}

func (x *UpsertItem) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertItem.ProtoReflect.Descriptor instead.
func (*UpsertItem) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpsertItem) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *UpsertItem) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type UpsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *UpsertItem            `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertRequest) Reset() {
	*x = UpsertRequest{}
	mi := &file_vector_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertRequest) ProtoMessage() {}

func (x *UpsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertRequest.ProtoReflect.Descriptor instead.
func (*UpsertRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertRequest) GetItem() *UpsertItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertResponse) Reset() {
	*x = UpsertResponse{}
	mi := &file_vector_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertResponse) ProtoMessage() {}

func (x *UpsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertResponse.ProtoReflect.Descriptor instead.
func (*UpsertResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{3}
}

type UpsertBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UpsertItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertBatchRequest) Reset() {
	*x = UpsertBatchRequest{}
	mi := &file_vector_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBatchRequest) ProtoMessage() {}

func (x *UpsertBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBatchRequest.ProtoReflect.Descriptor instead.
func (*UpsertBatchRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertBatchRequest) GetItems() []*UpsertItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpsertBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertBatchResponse) Reset() {
	*x = UpsertBatchResponse{}
	mi := &file_vector_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertBatchResponse) ProtoMessage() {}

func (x *UpsertBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertBatchResponse.ProtoReflect.Descriptor instead.
func (*UpsertBatchResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{5}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_vector_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_vector_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_vector_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{8}
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_vector_store_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_store_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_vector_store_proto_rawDescGZIP(), []int{9}
}

func (x *CountResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_vector_store_proto protoreflect.FileDescriptor

const file_vector_store_proto_rawDesc = "" +
	"\n" +
	"\x12vector_store.proto\x12\x05argus\"T\n" +
	"\fSearchResult\x12\x19\n" +
	"\braw_text\x18\x01 \x01(\tR\arawText\x12)\n" +
	"\x10similarity_score\x18\x02 \x01(\x01R\x0fsimilarityScore\"U\n" +
	"\n" +
	"UpsertItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\braw_text\x18\x02 \x01(\tR\arawText\x12\x1c\n" +
	"\tembedding\x18\x03 \x03(\x02R\tembedding\"6\n" +
	"\rUpsertRequest\x12%\n" +
	"\x04item\x18\x01 \x01(\v2\x11.argus.UpsertItemR\x04item\"\x10\n" +
	"\x0eUpsertResponse\"=\n" +
	"\x12UpsertBatchRequest\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.argus.UpsertItemR\x05items\"\x15\n" +
	"\x13UpsertBatchResponse\"B\n" +
	"\rSearchRequest\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"?\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.argus.SearchResultR\aresults\"\x0e\n" +
	"\fCountRequest\"%\n" +
	"\rCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count2\xf6\x01\n" +
	"\fShardService\x125\n" +
	"\x06Upsert\x12\x14.argus.UpsertRequest\x1a\x15.argus.UpsertResponse\x12D\n" +
	"\vUpsertBatch\x12\x19.argus.UpsertBatchRequest\x1a\x1a.argus.UpsertBatchResponse\x125\n" +
	"\x06Search\x12\x14.argus.SearchRequest\x1a\x15.argus.SearchResponse\x122\n" +
	"\x05Count\x12\x13.argus.CountRequest\x1a\x14.argus.CountResponseB\x1bZ\x19github.com/aepii/argus/pbb\x06proto3"

var (
	file_vector_store_proto_rawDescOnce sync.Once
	file_vector_store_proto_rawDescData []byte
)

func file_vector_store_proto_rawDescGZIP() []byte {
	file_vector_store_proto_rawDescOnce.Do(func() {
		file_vector_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_store_proto_rawDesc), len(file_vector_store_proto_rawDesc)))
	})
	return file_vector_store_proto_rawDescData
}

var file_vector_store_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_vector_store_proto_goTypes = []any{
	(*SearchResult)(nil),        // 0: argus.SearchResult
	(*UpsertItem)(nil),          // 1: argus.UpsertItem
	(*UpsertRequest)(nil),       // 2: argus.UpsertRequest
	(*UpsertResponse)(nil),      // 3: argus.UpsertResponse
	(*UpsertBatchRequest)(nil),  // 4: argus.UpsertBatchRequest
	(*UpsertBatchResponse)(nil), // 5: argus.UpsertBatchResponse
	(*SearchRequest)(nil),       // 6: argus.SearchRequest
	(*SearchResponse)(nil),      // 7: argus.SearchResponse
	(*CountRequest)(nil),        // 8: argus.CountRequest
	(*CountResponse)(nil),       // 9: argus.CountResponse
}
var file_vector_store_proto_depIdxs = []int32{
	1, // 0: argus.UpsertRequest.item:type_name -> argus.UpsertItem
	1, // 1: argus.UpsertBatchRequest.items:type_name -> argus.UpsertItem
	0, // 2: argus.SearchResponse.results:type_name -> argus.SearchResult
	2, // 3: argus.ShardService.Upsert:input_type -> argus.UpsertRequest
	4, // 4: argus.ShardService.UpsertBatch:input_type -> argus.UpsertBatchRequest
	6, // 5: argus.ShardService.Search:input_type -> argus.SearchRequest
	8, // 6: argus.ShardService.Count:input_type -> argus.CountRequest
	3, // 7: argus.ShardService.Upsert:output_type -> argus.UpsertResponse
	5, // 8: argus.ShardService.UpsertBatch:output_type -> argus.UpsertBatchResponse
	7, // 9: argus.ShardService.Search:output_type -> argus.SearchResponse
	9, // 10: argus.ShardService.Count:output_type -> argus.CountResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_vector_store_proto_init() }
func file_vector_store_proto_init() {
	if File_vector_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_store_proto_rawDesc), len(file_vector_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_store_proto_goTypes,
		DependencyIndexes: file_vector_store_proto_depIdxs,
		MessageInfos:      file_vector_store_proto_msgTypes,
	}.Build()
	File_vector_store_proto = out.File
	file_vector_store_proto_goTypes = nil
	file_vector_store_proto_depIdxs = nil
}
